services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container-teste
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    networks:
      - aula04

  postgres:
    image: postgres
    container_name: postgresDB-teste
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: escola_db
      POSTGRES_PASSWORD: postgres
    networks:
      - aula04

networks:
  aula04:
    driver: bridge